openworm/geppetto-client

js/communication/MessageSocket.js
js/components/interface/3dCanvas/Canvas.js
js/components/interface/3dCanvas/SceneController.js
js/components/interface/3dCanvas/ThreeDEngine.js
js/components/interface/menu/MenuPopper.js
js/components/interface/menu/MenuSection.js
js/components/interface/menu/MenuSingleItem.js
js/components/widgets/stackViewer/StackViewerComponent.js

Latest frontend repo from release_march_2019 branch ported to geppetto-client.
- menu warning resolved using ContainerProps to propagate the custom handler to nested menus
- VFB March Release: style improvements, fixed issue with maximised tabset and menu not visible anymore
- Bug #312 - Canvas items in the scene at startup too far and not centered
- Canvas reopening fixed
- VFB reopening obj instance after delete the parent instance the first time was not loading the obj element properly, scene controller implementing now a function to check if an instance is present in the scene and linked to the display method
- VFB Menu css polishing
- Canvas: selection improved with point clouds

Feature merge latest frontend with client

---

package.json

lock react-dnd version

---

js/components/interface/spotlight/spotlight.js

- [NA ] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

Hot fix for spotlight SOLR query needing replaceALL

---

js/components/interface/query/query.js

- [NA ] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

Hot fix for query search SOLR query needing replaceALL

---

js/communication/geppettoJupyter/GeppettoJupyterUtils.js
js/pages/geppetto/GEPPETTO.Events.js

Trigger Python command exec error event

---

js/components/interface/query/queryBuilder.js

- [Planned] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
Resolves https://github.com/openworm/geppetto-client/issues/56

quoting fields in CSV

---

js/components/interface/plot/PlotComponent.js
js/components/interface/plot/PlotHeader.js
js/components/interface/plot/configuration/plotConfiguration.js

Add geppetto buttons

---

js/components/interface/plot/PlotHeader.js

Remove React Unique key for list objects warning

---

js/components/interface/menu/Menu.js

Feature/62: Fixed empty handler string

---

js/components/interface/3dCanvas/OBJLoader.js
js/components/interface/3dCanvas/ThreeDEngine.js
js/components/widgets/stackViewer/StackViewerComponent.js

Feature/65: OBJ loader new material

---

js/components/interface/query/queryBuilder.js

See https://github.com/openworm/geppetto-client/blob/development/js/components/interface/spotlight/spotlight.js#L109
Ref https://github.com/VirtualFlyBrain/VFB2/issues/201
- IN PROGRESS Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

HOTFIX for incorrect replace as multiple items for query search

---

js/components/interface/query/queryBuilder.js

- IN PROGRESS Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
This should be conditional if the first one fails from looking at the spotlight code but in its current state is clearing the settings including the custom sorter causing part of https://github.com/VirtualFlyBrain/VFB2/issues/201

HOT FIX Removing the secondary initialization

---

.travis.yml

Closes #77 
Add travis and run linting

Add travis #77

---

js/components/interface/pythonConsole/PythonConsole.js

Hide the initial loading of the notebook with material-ui *Circular Progress*

Add spinning wheel when notebook is loading

---

js/components/interface/query/queryBuilder.js
js/pages/dashboard/js/libs/jasmine/jasmineAdapter.js

It refers to [this](https://github.com/VirtualFlyBrain/geppetto-vfb/issues/374) .
- Images (in case of a slider only the first) added to the csv download for the query builder results.

Add images to the query results csv download

---

js/components/interface/plot/PlotComponent.js
js/components/interface/plot/PlotHeader.js
js/components/interface/plot/configuration/plotConfiguration.js
package-lock.json
package.json

Contains a pure react implementation for #28

Added PlotComponent (pure react)

---

js/components/interface/pythonConsole/PythonConsole.js

Rebooted with a clean history. Please @rodriguez-facundo check if I have missed something

#281 Added loader to python console

---

js/components/interface/controlPanel/controlpanel.js
js/components/interface/moviePlayer/MoviePlayer.js
js/components/interface/tree/Tree.js
js/components/interface/tutorial/Tutorial.js

- Some changes to the tree components to include new props required.
- Fixed an issue with the controlpanel by simply checking the eval in a try or initializing to false in case of error.
- Fixed error with tutorial component (but I am pretty sure this was already in another PR of mine, same stuff related to the webpack configuration upgrade that I had to fix).

Tree Browser improvements

---

js/components/widgets/stackViewer/StackViewerComponent.js

- Stackviewer component re-opening bug fixed.
Closes #115

stackviewer bug on reopening fixed

---

js/components/widgets/popup/ButtonBarComponent.js

- Component refactored to get rid of the create-class pattern that was creating me some issues in using the material-ui components and style.
- Material-UI tooltip instead of custom one.
Closes #116

tooltip re-alignment between buttonbar, focusterm and other components

---

js/components/interface/controlPanel/controlpanel.js
js/components/widgets/stackViewer/StackViewerComponent.js

Merges feature/101 into this branch, which has a pending PR to development. 
Changes to controlpanel and stackviewer made to fix deletion issues.

Geppetto vfb/feature/218

---

js/components/interface/graph-visualization/Graph.js

Fixed graph labels

---

js/geppettoModel/ModelFactory.js

Adding missing stuff from previous version

#132 fix ModelFactory

---

js/geppettoModel/ModelFactory.js

Support is not complete yet but may still be merged temportarely

#161 Added tags to geppetto model

---

package-lock.json
package.json

Release 2.1.0 in package.json

---

js/components/interface/query/queryBuilder.js

Resolves #158
- [TBD in geppetto-vfb] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

fix/158 Handling all potential image types in CSV download

---

js/components/interface/query/customComponents/slideshowImageComponent.js

Resolves #156
- [TBD in geppetto-vfb] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

Don't close query results if shift is pressed

---

js/components/interface/controlPanel/ControlPanel.less
js/components/interface/controlPanel/controlpanel.js
js/components/interface/query/query.less
js/components/interface/query/queryBuilder.js
js/components/interface/spotlight/spotlight.js
js/components/interface/spotlight/spotlight.less

Optional icon to close Querybuilder/ControlPanel/Spotlight

---

js/components/widgets/stackViewer/StackViewerComponent.js

wiping stack on reduction in size

---

js/components/interface/query/query.less
js/components/interface/spotlight/spotlight.js
js/components/interface/spotlight/spotlight.less

fix close icon position

---

js/components/interface/query/customComponents/slideshowImageComponent.js
js/components/interface/query/query.less

Feature/489 in VFB 

---

js/common/GEPPETTO.Resources.js
js/communication/GEPPETTO.GlobalHandler.js
js/communication/MessageHandler.js
js/communication/MessageSocket.js

Fix/177 into VFB

---

js/pages/geppetto/geppetto.ejs

Splash and loading text styling

---

package.json

reverting react-rnd to previous version used since not need to upgrade

---

js/components/interface/3dCanvas/Canvas.js
js/components/interface/3dCanvas/ThreeDEngine.js
js/geppettoModel/ModelFactory.js
js/pages/geppetto/GEPPETTO.Events.js
package.json

latest fixes from Feature/232

---

js/components/widgets/stackViewer/StackViewerComponent.js

- [TBA] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

Fix/179 Scaling image requests to > or match display scaling and support for hide/show layers

---

package-lock.json
package.json

PR for patch release - the base master is set on purpose since we will need a patch release of the latest with this fix on top.

#247 fix underscore version for patch release

---

js/components/interface/search/datasources/SOLRclient.tsx

modifying SOLRClient results editor function as requested for VFB

---

js/components/interface/search/Search.tsx
js/components/interface/search/style/search.less
tsconfig.json

latest from Feature/200

---

js/geppettoModel/ModelFactory.js

It was breaking for Instances with no dot in the path

#277 Trigger Geppetto event 'Instance_added'

---

__tests__/ModelFactory.test.js

Feature/277 Added coverage

---

js/geppettoModel/ModelFactory.js

#283 removed error message

---

js/pages/geppetto/geppetto.ejs

#287 fix scroll bar on splash screen

---

js/components/widgets/stackViewer/StackViewerComponent.js

Adding latest tweaks to loading timing

---

js/components/interface/tree/Tree.js

Adds controls to Tree component if given in properties. Needed for VFB issue : https://github.com/VirtualFlyBrain/geppetto-vfb/issues/567

Add controls to Tree component

---

js/components/widgets/stackViewer/StackViewerComponent.js

adding a delayed home on orthoganal view change

---

js/components/widgets/stackViewer/StackViewerComponent.js

syntax fix to fix the plane view

---

js/components/interface/3dCanvas/Canvas.js
js/components/interface/3dCanvas/ThreeDEngine.js

removing animation improvements

---

js/components/interface/3dCanvas/Canvas.js
js/components/interface/3dCanvas/ThreeDEngine.js
js/components/widgets/stackViewer/StackViewerComponent.js

updating for merge back

---

js/common/GEPPETTO.Resources.js
js/components/interface/3dCanvas/Canvas.js
js/components/interface/3dCanvas/ThreeDEngine.js
js/components/interface/listViewer/ListViewer.js
js/components/interface/listViewer/utils/Griddle.js
js/components/interface/loadingSpinner/LoadingSpinner.js
js/components/interface/query/customComponents/slideshowImageComponent.js
js/components/interface/spotlight/spotlight.js
js/components/interface/tree/Tree.js
js/components/widgets/stackViewer/StackViewerComponent.js
js/geppettoModel/ModelFactory.js
js/pages/geppetto/geppetto.ejs

Vf bv2.2.0.1
